ALTER DATABASE [AdventureWorks2014_2]
 SET COMPATIBILITY_LEVEL = 80
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Table_1] (
		[dg]     [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[gh]     [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Table_1] SET (LOCK_ESCALATION = TABLE)
GO
